name: 'Labeling by GPT'
description: 'Puts labels to Issues'

branding:
  color: orange
  icon: tag

inputs:
  openai-api-key:  # id of input
    description: 'OpenAI API Key'
    required: true
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: dist/index.js