on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - shell: bash
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git status

            echo "::error::Unstaged changes detected."
          fi